# TODO: forma de que se pueda cambiar esto
name: ${CONTAINER_NAME}

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, front]

    steps:
      - name: Deploy
        # TODO: forma de que se pueda cambiar esto
        run: /root/apps/deploy.sh ${CONTAINER_NAME}
