# TODO: forma de que se pueda cambiar esto
name: ${CONTAINER_NAME}

on:
  push:
    branches: ["test"]

jobs:
  deploy:
    runs-on: [self-hosted, test]

    steps:
      - name: Deploy
        # TODO: forma de que se pueda cambiar esto
        run: /root/apps/deploy.sh ${CONTAINER_NAME}
